version: '2'
services:
    filrouge0-app:
        image: filrouge0
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://filrouge0-mysql:3306/filrouge0?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    filrouge0-mysql:
        extends:
            file: mysql.yml
            service: filrouge0-mysql
